### ISSUE TITLE
Which version of hikari-cp should be used with clojure.jdbc?

### ISSUE THREAD

**Issue by zeroDivisible** [niwibe/clojure.jdbc#21]
Hi,

Just wanted to ask - I've seen that docs are specifying to use [``0.13.0`` version of hikari-cp](http://niwibe.github.io/clojure.jdbc/latest/#_hikaricp). The latest version of hikari-cp, advertised in [README for it](https://github.com/tomekw/hikari-cp) appears to be ``1.1.1``. Is it maybe the case that docs for ``clojure.jdbc`` should be updated or is there maybe a reason why previous version of ``hikari-cp`` is preferred?

Thanks! :)

**Comment by niwibe** [comment]
hi @zeroDivisible the documentation refers to hikari-cp concrete version as example. After release of clojure.jdbc documentation, hikari-cp has released new versions that are not reflected in clojure.jdbc documention. Nothing more.

You can use any version of hikari-cp. And in the next clojure.jdbc update, I will update the hikari-cp in the doc. Also, you can send a pr with a little fix and I gladly accept it ;)

**Comment by zeroDivisible** [comment]
@niwibe thanks! :D 

I thought that this is the case, just wanted to confirm. I'm a total Clojure newbie, so just trying to play it safe :D 

(I created PR, btw).

Thanks for this project:)
